name: Prettify

on:
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      # - run: echo action ${{ github.action }}
      # - run: echo action_path ${{ github.action_path }}
      # - run: echo actor ${{ github.actor }}
      # - run: echo base_ref ${{ github.base_ref }}
      # - run: echo event_name ${{ github.event_name }}
      # - run: echo event_path ${{ github.event_path }}
      # - run: echo head_ref ${{ github.head_ref }}
      # - run: echo job ${{ github.job }}
      # - run: echo ref ${{ github.ref }}
      # - run: echo ref_name ${{ github.ref_name }}
      # - run: echo ref_protected ${{ github.ref_protected }}
      # - run: echo ref_type ${{ github.ref_type }}
      # - run: echo repository ${{ github.repository }}
      # - run: echo repository_owner ${{ github.repository_owner }}
      # - run: echo run_id ${{ github.run_id }}
      # - run: echo run_number ${{ github.run_number }}
      # - run: echo run_attempt ${{ github.run_attempt }}
      # - run: echo server_url ${{ github.server_url }}
      # - run: echo sha ${{ github.sha }}
      # - run: echo token ${{ github.token }}
      # - run: echo workflow ${{ github.workflow }}
      # - run: echo workspace ${{ github.workspace }}

      # - run: echo base_ref ${{ github.base_ref }}
      # - run: echo head_ref ${{ github.head_ref }}
      # - run: echo ref ${{ github.ref }}
      # - run: echo ref_name ${{ github.ref_name }}
      # - run: echo repository ${{ github.repository }}
      # - run: echo ${{ github }}

      - name: Checkout
        uses: actions/checkout
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.ref_name }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0


      - name: Check branches
        run: git branch --all
      

      # - name: Prettify code
      #   uses: creyD/prettier_action@v4.0
      #   with:
      #     # This part is also where you can pass other options, for example:
      #     commit_message: prettify the code \#tools-not-rules
      #     prettier_options: --write *.ts src/**/*.ts
      #     only_changed: True
